version: '3.8'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: Dockerfile

    #container_name: webapi
    ports:
      - "8080:80"
    #volumes:
    #  - .:/app
    #working_dir: /app
    #command: ["dotnet", "run"]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__MySql=Server=db;Port=3306;Database=mydb;user=root;password=my-secret-pw
    depends_on:
      - db

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
